spring: 
 profiles:
  active: dev
---
server: 
 port: 8888
spring: 
 application: 
  name: microservice-config-dev
 profiles: dev

---
server: 
 port: 9999
spring: 
 application: 
  name: microservice-config-test
 profiles: test