spring: 
 profiles:
  active: 
  - dev
---
server: 
 port: 7001
eureka: 
 instance: 
  hostname: eureka7001
 client: 
  register-with-eureka: false
  fetch-register: false
  service-url: 
   defaultZone: http://eureka7001:7001/eureka/
spring: 
 profiles: dev
---
server: 
 port: 7002
eureka: 
 instance: 
  hostname: eureka7002
 client: 
  register-with-eureka: false
  fetch-register: false
  service-url: 
   defaultZone: http://eureka7002:7002/eureka/
spring: 
 profiles: dev
